language: java
jdk: oraclejdk8
sudo: false
dist: trusty
install: true
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Raouf25_Spring-Boot-Web-App  -Dsonar.organization=raouf25-github  -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=71a0fe9c1889169215713079d21713657d645c6f
- mvn cobertura:cobertura
after_success:
- bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
before_install:
- chmod +x mvnw
notifications:
  email:
    recipients:
    - makhlouf.raouf+travis@gmail.com
    - jarraymohamed92@hotmail.fr
    on_failure: always